"""Runtime shadows of formally specified operation contracts.

The Lean files own the mathematical distinction between exact operation
semantics and the weaker relation established by local validation.  These
immutable values make that same distinction inspectable at the Python
boundary.  They are plans and audit data, not proof objects.

Saturation and elimination are the two exercised pilots. Their operation-local
checks stay separate from claim-side transport obligations: a correct output is
not by itself a proof that an arbitrary proposition can be stated at the target.
"""

from dataclasses import dataclass
from types import MappingProxyType

from . import kernel as K


@dataclass(frozen=True)
class ValidationObligation:
    """One independently checkable part of an operation's local guarantee."""

    name: str
    verifier_subject: str
    verifier_function: str
    establishes: str


@dataclass(frozen=True)
class OperationContract:
    """Backend-neutral semantic and validation boundary for an operation."""

    kind: str
    source_sort: str
    target_sort: str
    parameters: tuple
    preconditions: tuple
    semantic_relation: str
    edge_type: str
    built_endpoint: str
    source_endpoint: str
    transport_reason: str
    checked_obligations: tuple
    transport_obligations: tuple
    open_obligations: tuple
    licensed_consequences: tuple

    def __post_init__(self):
        if self.edge_type not in K.ALL_TYPES:
            raise ValueError("%s names unknown edge type %s"
                             % (self.kind, self.edge_type))
        if {self.built_endpoint, self.source_endpoint} != {"src", "dst"}:
            raise ValueError("%s must orient built and source endpoints"
                             % self.kind)
        names = [obligation.name for obligation in self.checked_obligations]
        if len(names) != len(set(names)):
            raise ValueError("%s repeats a checked obligation" % self.kind)
        if not self.semantic_relation or not self.checked_obligations:
            raise ValueError("%s is missing semantics or validation" % self.kind)

    @property
    def derivation(self):
        return self.edge_type, self.transport_reason


SATURATION = OperationContract(
    kind="SaturateClosure",
    source_sort="ideal in an exact polynomial ring",
    target_sort="ideal in the same exact polynomial ring",
    parameters=("polynomial f",),
    preconditions=(
        "source and built ideals are interpreted in the same ring",
        "f is an expression in that ring",
        "the built ideal is generated by exactly the recorded output generators",
    ),
    semantic_relation="I(built) = I(source) : f^oo",
    edge_type=K.NECESSARY_CONDITION,
    built_endpoint="src",
    source_endpoint="dst",
    transport_reason=(
        "I : f^oo contains I, so the saturated model is cut by more "
        "equations; returning to the ambient model drops them"
    ),
    checked_obligations=(
        ValidationObligation(
            "source_containment",
            "edge",
            "containment",
            "I(source) is contained in I(built)",
        ),
        ValidationObligation(
            "no_invented_generators",
            "operation",
            "operation_output",
            "every recorded generator of I(built) has a certified witness "
            "in I(source) : f^oo",
        ),
    ),
    transport_obligations=(),
    open_obligations=(
        "I(source) : f^oo is contained in I(built) (output completeness)",
    ),
    licensed_consequences=(
        "the entire built ideal is contained in I(source) : f^oo "
        "(generator certificates lift through ideal generation)",
        "source ideal identities hold on the built model "
        "(NECESSARY_CONDITION/AGAINST)",
    ),
)


ELIMINATION = OperationContract(
    kind="Eliminate",
    source_sort="ideal in source exact polynomial ring R",
    target_sort="ideal in retained-coordinate exact polynomial ring S",
    parameters=(
        "coordinate inclusion S -> R",
        "eliminated/retained variable partition",
    ),
    preconditions=(
        "retained and eliminated variables are disjoint and partition the source ring",
        "source and built rings have the same exact coefficient domain",
        "the built ideal is generated by exactly the recorded output generators",
    ),
    semantic_relation="I(built) = inclusion^-1(I(source))",
    edge_type=K.IMAGE_CLOSURE,
    built_endpoint="dst",
    source_endpoint="src",
    transport_reason=(
        "exact elimination contracts the source ideal to the retained-coordinate "
        "ring; a polynomial section additionally supplies target-point lifts, "
        "while a pure Groebner certificate supplies only ideal equality"
    ),
    checked_obligations=(
        ValidationObligation(
            "generator_expressibility",
            "operation",
            "operation_output",
            "every recorded output generator is an expression in the retained ring",
        ),
        ValidationObligation(
            "generator_source_membership",
            "operation",
            "operation_output",
            "every recorded output generator maps into the source ideal",
        ),
        ValidationObligation(
            "section_completeness",
            "elimination",
            "elimination_section",
            "a polynomial retraction fixes the retained ring and carries the "
            "entire source ideal into the recorded target ideal",
        ),
        ValidationObligation(
            "groebner_completeness",
            "elimination",
            "elimination_groebner",
            "a pure-lex basis certificate checks each recorded source generator's "
            "basis-span identity, "
            "bounded S-pair representation, and retained-basis membership",
        ),
    ),
    transport_obligations=(
        ValidationObligation(
            "retained_coordinate_expressibility",
            "claim",
            "structured_condition",
            "the source predicate is an exact ZERO/NONZERO conjunction whose "
            "expressions also parse in the retained-coordinate target ring",
        ),
    ),
    open_obligations=(
        "contraction completeness beyond Q/prime fields, bounded pure lex, and polynomial sections",
        "point-surjectivity beyond global polynomial sections needs a separately typed certificate",
        "structured condition rewriting and expressibility across composed coordinate changes",
    ),
    licensed_consequences=(
        "the entire built ideal is contained in the contraction of the source ideal",
        "target identities pull back to source identities (IMAGE_CLOSURE/AGAINST)",
        "source points map to target points, so target emptiness implies source emptiness",
        "a verified section or Groebner certificate plus no-invention licenses source-derived retained-ring identities along",
        "a verified section plus no-invention supplies point-surjective image authority over the declared coefficient algebra",
        "point-surjectivity transports direct, structured retained-coordinate predicates, including NONZERO atoms",
    ),
)


CONTRACTS = MappingProxyType({
    SATURATION.kind: SATURATION,
    ELIMINATION.kind: ELIMINATION,
})


def for_operation(kind):
    """Return the formalization-backed runtime contract, if one exists."""

    return CONTRACTS.get(kind)
