/-
# Operation contracts: semantics are stronger than local validation

An operation contract must keep three things separate:

  * the mathematical relation the operation intends to construct;
  * the weaker guarantee established by the available local checkers;
  * the transport consequences licensed by that checked guarantee.

If those collapse into one predicate, a successful translation-validation
check can silently become a theorem that the backend computed the complete
mathematical object.  Saturation is the first executable instance because the
current runtime makes the distinction concrete:

    source containment       I ⊆ J
    generator certificates  recorded generators of J lie in I : f^∞
    exact saturation         J = I : f^∞

The first two are checked independently.  They do not imply the third.
-/

import GrandPortage.Localization

namespace GrandPortage

universe u v w

/-- A backend-neutral semantic contract for one model-changing operation.

    `semanticRelation` says what a mathematically exact implementation means.
    `checkedGuarantee` says only what the current translation validators earn.
    The required theorem points from exact semantics to the checked guarantee,
    deliberately not in the tempting and generally false reverse direction.

    Preconditions may mention both endpoints. A computed target has
    well-formedness obligations of its own; forcing those into source data would
    hide exactly the output boundary this record is meant to expose. -/
structure OperationContract (Params : Type u) (Source : Type v)
    (Target : Type w) where
  precondition : Params → Source → Target → Prop
  semanticRelation : Params → Source → Target → Prop
  checkedGuarantee : Params → Source → Target → Prop
  semantics_entails_checked :
    ∀ p source target,
      precondition p source target →
      semanticRelation p source target →
      checkedGuarantee p source target

/-- The ideal generated by `generators`, characterized by its universal
    property inside a chosen family of admissible ideal predicates.

    `Ideal` is intentionally only a predicate in this Mathlib-free model.  The
    `isIdeal` parameter restores exactly the missing algebraic distinction:
    generated membership means membership in every admissible ideal containing
    the generators. -/
def GeneratedIdeal {R : Type u} (isIdeal : Ideal R → Prop)
    (generators : R → Prop) : Ideal R :=
  fun g => ∀ J, isIdeal J → (∀ x, generators x → J x) → J g

/-- Every named generator belongs to the ideal it generates. -/
theorem generator_mem_generated {R : Type u} {isIdeal : Ideal R → Prop}
    {generators : R → Prop} {g : R} (hg : generators g) :
    GeneratedIdeal isIdeal generators g := by
  intro J _ contains
  exact contains g hg

/-- The generated ideal is contained in every admissible ideal containing its
    generators.  This is the bridge the predicate-only model previously lacked. -/
theorem generatedIdeal_least {R : Type u} {isIdeal : Ideal R → Prop}
    {generators : R → Prop} {J : Ideal R}
    (hJ : isIdeal J) (contains : ∀ g, generators g → J g) :
    IdealGrows (GeneratedIdeal isIdeal generators) J := by
  intro g generated
  exact generated J hJ contains

/-- The semantic parameters of a saturation run include the polynomial
    inverted, the generators recorded at the runtime boundary, and the family
    of predicates that count as ideals in the source ring. -/
structure SaturationParams (R : Type u) where
  f : R
  recordedGenerator : R → Prop
  isIdeal : Ideal R → Prop

/-- The exact meaning of a saturation result `J`: membership in `J` is
    precisely membership in `I : f^∞`. -/
def SaturationSemantics {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R) : Prop :=
  ∀ g, J g ↔ SatMem I p.f g

/-- Endpoint facts needed to interpret the local checks.  Both endpoints and
    the semantic saturation are admissible ideals, and the output predicate is
    exactly the ideal generated by the list recorded at the runtime boundary. -/
structure SaturationPrecondition {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R) : Prop where
  one_mul : ∀ g : R, 1 * g = g
  source_is_ideal : p.isIdeal I
  output_is_ideal : p.isIdeal J
  saturation_is_ideal : p.isIdeal (fun g => SatMem I p.f g)
  output_generated :
    ∀ g, J g ↔ GeneratedIdeal p.isIdeal p.recordedGenerator g

/-- Exactly what Grand Portage's two independent runtime checks establish.

    `containsSource` is the edge-containment check. `noInventedGenerator` is
    the operation-output certificate for each recorded generator.  The theorem
    `saturation_checked_no_invented_elements` combines these local facts with
    `output_generated` to derive the stronger ideal-level sound envelope. -/
structure SaturationChecked {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R) : Prop where
  containsSource : IdealGrows I J
  noInventedGenerator : ∀ g, p.recordedGenerator g → SatMem I p.f g

/-- Ordinary ideal membership gives saturation membership whenever `1` acts
    as a left identity.  This generalizes `mem_satMem` beyond `Int` without
    importing Mathlib's algebraic hierarchy. -/
theorem mem_satMem_of_one_mul {R : Type u} [Mul R] [OfNat R 1]
    (one_mul : ∀ g : R, 1 * g = g) {I : Ideal R} {f g : R}
    (h : I g) : SatMem I f g :=
  ⟨1, PowerOf.one, by rw [one_mul]; exact h⟩

/-- Exact saturation entails both checks for every well-formed recorded
    generator list. -/
theorem saturation_semantics_entails_checked
    {R : Type u} [Mul R] [OfNat R 1]
    (p : SaturationParams R) (I J : Ideal R)
    (pre : SaturationPrecondition p I J)
    (h : SaturationSemantics p I J) :
    SaturationChecked p I J := by
  constructor
  · intro g hg
    exact (h g).2 (mem_satMem_of_one_mul pre.one_mul hg)
  · intro g recorded
    apply (h g).1
    apply (pre.output_generated g).2
    exact generator_mem_generated recorded

/-- Generator certificates lift to every element of the recorded output ideal
    once the endpoint is known to be generated by exactly those generators.

    This proves the sound envelope `J ⊆ I : f^∞`.  It does not prove the open
    completeness direction `I : f^∞ ⊆ J`. -/
theorem saturation_checked_no_invented_elements
    {R : Type u} [Mul R] [OfNat R 1]
    {p : SaturationParams R} {I J : Ideal R}
    (pre : SaturationPrecondition p I J)
    (checked : SaturationChecked p I J) :
    IdealGrows J (fun g => SatMem I p.f g) := by
  intro g hg
  have generated := (pre.output_generated g).1 hg
  exact generated
    (fun x => SatMem I p.f x)
    pre.saturation_is_ideal
    checked.noInventedGenerator

/-- Saturation as an operation-contract instance. -/
def saturationContract {R : Type u} [Mul R] [OfNat R 1] :
    OperationContract (SaturationParams R) (Ideal R) (Ideal R) where
  precondition := SaturationPrecondition
  semanticRelation := SaturationSemantics
  checkedGuarantee := SaturationChecked
  semantics_entails_checked := saturation_semantics_entails_checked

/-! ## What the checked guarantee licenses -/

/-- Source identities remain valid on the checked saturation result.  This is
    the `NECESSARY_CONDITION / AGAINST / IDENTITY` theorem for saturation,
    derived from the independently checked `containsSource` field. -/
theorem saturation_checked_transports_identity_against
    {R : Type u} [Mul R] [OfNat R 1] [Sub R]
    {p : SaturationParams R} {I J : Ideal R}
    (checked : SaturationChecked p I J) {lhs rhs : R} :
    EqMod I lhs rhs → EqMod J lhs rhs :=
  eqMod_against checked.containsSource

/-! ## And what it does not license -/

/-- A single recorded generator for the ideal `(6)`. -/
def sixGenerator : Int → Prop := fun n => n = 6

/-- Saturation at `2`, with `(6)` recorded by its generator `6`. -/
def sixesSaturationIdeal : Ideal Int := fun g => SatMem sixes 2 g

/-- A tiny admissible-ideal family sufficient to exercise the universal
    generated-ideal bridge on the concrete `(6)` counterexample. -/
def sixesIdealTheory : Ideal Int → Prop :=
  fun J => J = sixes ∨ J = sixesSaturationIdeal

/-- In that family, the ideal generated by `6` is exactly `(6)`. -/
theorem sixes_is_generated :
    ∀ g, sixes g ↔ GeneratedIdeal sixesIdealTheory sixGenerator g := by
  intro g
  constructor
  · intro hg J hJ contains
    rcases hJ with hJ | hJ
    · rw [hJ]
      exact hg
    · rw [hJ]
      exact mem_satMem hg
  · intro generated
    apply generated sixes (Or.inl rfl)
    intro x recorded
    simp only [sixGenerator] at recorded
    subst x
    exact ⟨1, by omega⟩

/-- Saturation at `2`, with `(6)` recorded by its generator `6`. -/
def sixesSaturationParams : SaturationParams Int where
  f := 2
  recordedGenerator := sixGenerator
  isIdeal := sixesIdealTheory

/-- The recorded generator really belongs to the declared output ideal. -/
theorem sixes_saturation_precondition :
    SaturationPrecondition sixesSaturationParams sixes sixes := by
  refine {
    one_mul := Int.one_mul
    source_is_ideal := Or.inl rfl
    output_is_ideal := Or.inl rfl
    saturation_is_ideal := Or.inr rfl
    output_generated := sixes_is_generated
  }

/-- The unchanged ideal `(6)` passes both local checks: it contains the source
    and its recorded generator has a saturation witness. -/
theorem sixes_checked_as_output :
    SaturationChecked sixesSaturationParams sixes sixes := by
  constructor
  · intro g hg
    exact hg
  · intro g recorded
    simp only [sixesSaturationParams, sixGenerator] at recorded
    subst g
    exact mem_satMem ⟨1, by omega⟩

/-- The same local checks now earn an ideal-level soundness envelope: every
    element generated by the recorded output lies in the true saturation. -/
theorem sixes_checked_has_no_invented_elements :
    IdealGrows sixes sixesSaturationIdeal :=
  saturation_checked_no_invented_elements
    sixes_saturation_precondition sixes_checked_as_output

/-- But that checked output is not the exact saturation: `3` is in
    `(6) : 2^∞` and not in `(6)`. Thus local validation cannot be promoted to
    exact operation semantics. -/
theorem checked_does_not_imply_saturation_semantics :
    ¬ SaturationSemantics sixesSaturationParams sixes sixes := by
  intro h
  exact three_not_mem_sixes ((h 3).2 three_satMem_sixes)

/-- Even exact saturation does not let a derived identity travel back to the
    ambient ideal.  This pins the refused ALONG direction independently of the
    implementation or its local checker. -/
theorem exact_saturation_does_not_transport_identity_along :
    let saturated : Ideal Int := fun g => SatMem sixes 2 g
    SaturationSemantics sixesSaturationParams sixes saturated ∧
      EqMod saturated 3 0 ∧ ¬ EqMod sixes 3 0 := by
  dsimp [SaturationSemantics, sixesSaturationParams]
  constructor
  · intro g
    rfl
  constructor
  · simpa [EqMod] using three_satMem_sixes
  · simpa [EqMod] using three_not_mem_sixes

end GrandPortage